### ISSUE TITLE
Unable to edit images in wp backend - Uncaught ArgumentCountError on callback_wp_save_image_editor_file

### ISSUE THREAD

**Issue by renrizzolo** [gatsbyjs/wp-gatsby#106]
Hello guys,
I'm having an issue with image editing (e.g cropping) causing a fatal error.

The error happens when pressing save after doing an image edit (crop, scale, flip, resize etc) – admin-ajax gets a `500` status.
I've checked and confirmed this is happening on a fresh install on a sepapate environment (local) as well.

```
PHP 7.3.21

WP 5.4.4
WP Gatsby 0.9.2
```

Here is the error log and stack trace:
```
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function WPGatsby\\ActionMonitor\\Monitors\\MediaMonitor::callback_wp_save_image_editor_file(), 
1 passed in /my/site/wp-includes/class-wp-hook.php on line 289 and exactly 5 expected in 
/my/site/wp-content/plugins/wp-gatsby---latest/src/ActionMonitor/Monitors/MediaMonitor.php:136

Stack trace:
#0 /my/site/wp-includes/class-wp-hook.php(289): WPGatsby\\ActionMonitor\\Monitors\\MediaMonitor->callback_wp_save_image_editor_file(NULL)
#1 /my/site/wp-includes/plugin.php(206): WP_Hook->apply_filters(NULL, Array)
#2 /my/site/wp-admin/includes/image-edit.php(346): apply_filters('wp_save_image_e...', NULL, '/my/site...', Object(WP_Image_Editor_Imagick), 'image/jpeg', 27591)
#3 /my/site/wp-admin/includes/image-edit.php(853): wp_save_image_file('/my/site in /my/site/wp-content/plugins/wp-gatsby---latest/src/ActionMonitor/Monitors/MediaMonitor.php on line 136, referer: https://mysite.com/wp-admin/post.php?post=27591&action=edit
```

Let me know if you need any more info.

**Comment by wbrauneis** [comment]
Would be great to have this shipped soon.
