### ISSUE TITLE
Activating the plugin crashes an empty WordPress install

### ISSUE THREAD

**Issue by keironpeel** [gatsbyjs/wp-gatsby#209]
When seeking help with this issue, you may be asked for some of the following information:
WordPress version 5.8.2
Current theme: Twenty Twenty-One (version 1.4)
Current plugin: WP Gatsby (version 2.1.1)
PHP version 8.0.14

Error Details
=============
An error of type E_ERROR was caused in line 79 of the file /var/web/site/public_html/wp-content/plugins/wp-gatsby/vendor/ircmaxell/random-lib/lib/RandomLib/Source/MicroTime.php. Error message: Uncaught Error: Call to undefined function RandomLib\Source\getmypid() in /var/web/site/public_html/wp-content/plugins/wp-gatsby/vendor/ircmaxell/random-lib/lib/RandomLib/Source/MicroTime.php:79
Stack trace:
#0 /var/web/site/public_html/wp-content/plugins/wp-gatsby/vendor/ircmaxell/random-lib/lib/RandomLib/Factory.php(201): RandomLib\Source\MicroTime->__construct()
#1 /var/web/site/public_html/wp-content/plugins/wp-gatsby/vendor/ircmaxell/random-lib/lib/RandomLib/Factory.php(77): RandomLib\Factory->findSources(Object(SecurityLib\Strength))
#2 /var/web/site/public_html/wp-content/plugins/wp-gatsby/vendor/ircmaxell/random-lib/lib/RandomLib/Factory.php(122): RandomLib\Factory->getGenerator(Object(SecurityLib\Strength))
#3 /var/web/site/public_html/wp-content/plugins/wp-gatsby/src/Admin/Settings.php(163): RandomLib\Factory->getMediumStrengthGenerator()
#4 /var/web/site/public_html/wp-content/plugins/wp-gatsby/src/Admin/Settings.php(40): WPGatsby\Admin\Settings::generate_secret()
#5 /var/web/site/public_html/wp-includes/class-wp-hook.php(303): WPGatsby\Admin\Settings->set_default_jwt_key('')
#6 /var/web/site/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#7 /var/web/site/public_html/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#8 /var/web/site/public_html/wp-settings.php(578): do_action('init')
#9 /var/web/site/public_html/wp-config.php(95): require_once('/var/web/site/p...')
#10 /var/web/site/public_html/wp-load.php(50): require_once('/var/web/site/p...')
#11 /var/web/site/public_html/wp-admin/admin.php(34): require_once('/var/web/site/p...')
#12 /var/web/site/public_html/wp-admin/plugins.php(10): require_once('/var/web/site/p...')
#13 {main}
  thrown

**Comment by fbrill** [comment]
@keironpeel - I had the same problem on `php 8` downgrading to `php 7.4` worked for me.
